### PR TITLE
change path to docker-compose

### PR DESCRIPTION
**Pull request by rchacon1**
docker-compose file in prox-ui will be split in two.

### CODE REVIEW

**Comment by rchacon1** [comment]
docker network in docker-compose is causing an error. update to follow

**Comment by rchacon1** [comment]
not working. closing for now.

**Comment by rchacon1** [comment]
Update to pull request pipeline is valid

**Comment by epluntze** [comment]
:metal:

**Comment by lathrop-navisite** [comment]
:evergreen_tree:

**Pull request merged**
