### PR TITLE
Send slack message after deployment

### PR DESCRIPTION
**Pull request by rchacon1**
## Testing

- Remove `trigger: true` from `deployment.yml`
- Add pipeline to local concourse
- Manually trigger one of the deploys other than `prox-ui` to test the yaml anchors. Since you won't be able to reach target VM locally the job will fail.
- For successful run change task file path to something that will pass for example the repo's `unit.yml`

### CODE REVIEW

**Comment by rchacon1** [comment]
looking into this ^

**Comment by rchacon1** [comment]
code duplication reduced. ready for R/T

**Comment by rchacon1** [comment]
so weird

**Comment by jburrill** [comment]
LGTM 👍

**Pull request merged**
