### PR TITLE
Add prox-ui repo

### PR DESCRIPTION
**Pull request by NaviSteve**
Add prox-ui to the PR pipeline. Opened for @rchacon1

### CODE REVIEW

**Comment by NaviSteve** [comment]
👍

**Comment by rchacon1** [comment]
I'm going to include the e2e tests

**Comment by lathrop-navisite** [comment]
:dango: (pre-e2e tests)

**Comment by lathrop-navisite** [comment]
@rchacon1 How are you going to add the e2e tests? On each PR creation/commit? Do we want that? Or do we want them to happen at some other point in the process?

**Comment by rchacon1** [comment]
Im currently setting it up to run after unit tests.

**Comment by zwerheim** [comment]
+1

**Pull request merged**
